### ISSUE TITLE
ERROR: Bootloader cannot be downloaded from URL.

### ISSUE THREAD

**Issue by darrepac** [uxora-com/xpenology-docker#6]
I used the following docker-compose.yml file:

```
version: '3.3'

services:
  Xpenology:
    image: "uxora/xpenology:latest"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: Xpenology
    restart: always
    volumes:
      - /home/pascal/DSM/data:/datashare
    ports:
      - '5000:5000'
    environment:
      - RAM=512
      - DISK_SIZE=32G
      - 'BOOTLOADER_URL=http://synoboot.linkhere.fr/synoboot_103b_ds3615xs_virtio_9p.img'
      - BOOTLOADER_AS_USB=Y
      - VM_ENABLE_VIRTIO=Y
```
     
and got the following:
```
Creating Xpenology ... done
Attaching to Xpenology
Xpenology    | INFO: Start downloading bootloader from URL ...
Xpenology    | ERROR: Bootloader cannot be downloaded from URL.
```
